brenoprata10/nvim-highlight-colors

- README.md
- lua/nvim-highlight-colors/init.lua
I thought that maybe not everyone wants to always highlight css color names, so I added this simple option (defaults to `true`), this way users can easily choose whether they want it enabled or not.
I also changed the way default options get overwritten by user options, since I noticed that before if an option is `true` by default, the `or options.x` in
```lua
options.x = user_options.x ~= nil and user_options.x or options.x
```
always overwrites user's option.
> Add option for css named colors

- lua/nvim-highlight-colors/color/utils.lua
The issue was caused by the regex that was only applying for classes like bg-slate-500 and etc. Simply modified it and now works fine with text-white or bg-black.
> fixed issue with not highlighting white or black colors in tailwindcss

- lua/nvim-highlight-colors/color/patterns.lua
Since the `hex_regex` was capturing any sequence of 3 or more alphanumeric characters, there were some random highlights enabled in any filetype, such as `#keyword` was highlighted as Keyword, `#identifier` as Identifier, `#include` as Include and so on. Using the `%x` class, which stands for any hexadecimal character, this issue is fixed.
> Fix regex bug

- lua/nvim-highlight-colors/buffer_utils.lua
- lua/nvim-highlight-colors/utils.lua
Support quoted CSS colour names, e.g. colour defined in source code or JSON as strings.
> Add support for colour names enclosed in quotation marks

- lua/nvim-highlight-colors/init.lua
I noticed that running `require("nvim-highlight-colors").turnOff()` and then changing buffer, the color highlighting gets re-enabled due to this autocmd:
```lua
vim.api.nvim_create_autocmd({"BufEnter"}, {
callback = function ()
if load_on_start_up == true then
M.turn_on()
end
end,
})
```
The problem is that it relies on the `load_on_start_up` variable, which is set to `true` in the `setup` function and it never changes after that. So I replaced all its occurrencies with `is_loaded`, which gets actually updated inside the `turn_on` and `turn_off` functions.
I also applied a minor style change to the other two autocmds, where I removed the redundant `not`/`return`.
> Fix turn on/off behavior

- lua/nvim-highlight-colors/color/patterns.lua
Currently, the plugin highlights colours within words, which gets especially annoying when editing files in languages like C/C++ which make large use of these (`#define`) (#43)
This PR enforces word boundaries around hex colours so that it doesn't highlight these, while still highlighting isolated colours
Old behaviour:
New behaviour:
Uses a [frontier pattern](http://www.lua.org/manual/5.2/manual.html#6.4.1) to define the word boundaries
Fixes #43
> fix: only highlight hex colours at word boundaries

- README.md
- lua/nvim-highlight-colors/init.lua
- lua/nvim-highlight-colors/utils.lua
This pull request allows customising the virtual text symbol when using `render = 'virtual'`. Can't say I love the name `virtual_symbol`, perhaps you have a better suggestion.
If you do want to go forward with this feature, I'd be happy to add documentation for the virtual text behaviour, including this addition. No hard feelings if this is not something you want to support.
Thanks!
> feat: add `options.virtual_symbol`

- lua/nvim-highlight-colors/utils.lua
Fixes #63 
Managed to find the fix by looking at the code for [nvim-colorizer](https://github.com/NvChad/nvim-colorizer.lua)
> fix: virtual text highlight

- lua/nvim-highlight-colors/buffer_utils.lua
I accidentally opened a PDF file in my neovim session and got flooded with a ton of errors. This seems to be an issue with trying to match a string that's actually a binary blob. I added a couple checks to safely ignore these types of errors without causing issues.
> Fix protection of accidental blob strings getting mached

- README.md
- lua/nvim-highlight-colors/init.lua
Hello,
I've added an exclude option in the setup.
This option acts as a filter to exclude specific file types, such as lazy, notify, and alpha. The implementation is straightforward: it checks if the user has specified any file types to exclude, and if the current file type matches one of these, it disables highlights for the active buffer.
If anything needs to be changed, do not hesitate to tell me.
Thanks
> Add opts to disable highlights for specific filetypes

- README.md
- lua/nvim-highlight-colors/init.lua
This allows the user to configure excluded buftypes as well and makes the default exclusion for "terminal" buffers
> feat!: allow excluding filetypes and buftypes

- lua/nvim-highlight-colors/init.lua
solves https://github.com/brenoprata10/nvim-highlight-colors/issues/98
> fix: close if statement

- lua/nvim-highlight-colors/init.lua
- lua/nvim-highlight-colors/utils.lua
Fixes #110
Currently the highlight groups for the highlighting in the document collide with the highlight groups set in the `cmp` formatting function. This is totally fine if the user doesn't use the background highlighting but if they do then it will mess up the highlighting on both. This does a few things: 
1. Makes sure the highlight names only collide if they provide the same highlight group `fg` vs `fg-bg`
2. uses `default = true` to make sure that if the highlight group already exists it doesn't get overwritten, this technically will save performance on each display
> Fix highlight collisions

- README.md
This adds some a more explicit example of `lspkind` since the approaches to modifying the completion item is not the same
Fixes #111
> Add `lspkind.nvim` integration example

- README.md
- lua/nvim-highlight-colors/init.lua
This command allows users to easily find out, programmatically, if the plugin is actively highlighting colors codes or not.
Made as a follow up to https://github.com/brenoprata10/nvim-highlight-colors/issues/129
Feel free to rename the command or change the code in whichever way you like.
> Add is_active command

- lua/nvim-highlight-colors/init.lua
This removes the usage of a deprecated function in `nvim-cmp` and instead directly retrieves the `completion_item`. This also allows the entry to be passed in directly as a string to allow supporting the formatting of other completion engines like `blink.cmp`
> Remove use of deprecated `get_completion_item` and allow direct passing of an entry documentation

- lua/nvim-highlight-colors/init.lua
This adds a slight improvement to the extraction of information from the `entry` variable that protects against the `entry` being `nil`.
> Add protection if `entry` is a `nil` value

- README.md
- lua/nvim-highlight-colors/init.lua
This adds an example for `blink.cmp` integration to the README to help users get started. I also did some refactoring and performance improvements to the documentation retrieval while putting this together.
> Add documentation on `blink.cmp` integration

- README.md
- lua/nvim-highlight-colors/init.lua
This adds a new configuration option for setting a function to calculate if a buffer should be excluded or not. This could be used to implement the same stuff as `exclude_buftypes` or `exclude_filetypes`, but also enables more logic such as disabling for files above a certain size.
> Add `exclude_buffer` configuration function for calculating if buffer should be enabeld

- README.md
When I set up blink.cmp according to the README, I encountered an issue where all LSP kind icons disappeared. After investigating, I found the problem appears to be in this code:
```lua
if color_item and color_item.abbr then
icon = color_item.abbr
end
```
The issue occurs because `color_item.abbr` was returning an empty string, causing the condition to be true and overwriting `icon` with that empty string. As a result, no icons were displayed when `ctx.item.source_name` was `LSP`.
> docs(blink.cmp): correct color display logic for LSP completion items
